### ISSUE TITLE
Shaft Miner Jumpsuit Invisible

### ISSUE THREAD

**Issue by VladinXXV** [CapnMachaddish/Outpost-R505-Horizon#25]
### Round ID / Commit SHA

809

### Client Version

514.1751

### Description of the Issue

I joined as shaft miner and my jumpsuit was completely invisible. It appeared white (?) to someone else (I think they were seeing my underwear. I tried taking it off and putting it back on again several times, to no avail.
![image](https://user-images.githubusercontent.com/44104681/154173836-52f2c543-29e7-4fcb-9535-53bc640327de.png)
![image](https://user-images.githubusercontent.com/44104681/154173851-fe3ef251-424f-430c-b549-d4293435ba71.png)

### Reproduction Steps

1. Join as shaft miner.
2. Notice your suit is invisible.
3. Cry.

**Comment by CapnMachaddish** [comment]
Resolved - weird pre-rebase code jank.

**Comment by CapnMachaddish** [comment]
Oops
